version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  test-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-npm: false 
          install-yarn: true 
          lts: true 
workflows:
  test-workflow:
    jobs:
      - test-job